name: Build and Release Extension Charts

on:
  workflow_dispatch:
  release:  
    types: [prereleased, released]

defaults:
  run:
    shell: bash
    working-directory: ./

jobs:
  build-extension-charts:
    uses: rancher/dashboard/.github/workflows/build-extension-charts.yml@50e55803dd880fea4026dd5980d9801ee421eb5b # creators-pkg-3.0.11
    permissions:
      actions: write
      contents: write
      deployments: write
      pages: write
    with:
      target_branch: gh-pages
      tagged_release: ${{ github.ref_name }}
